######################################################################
# Automatically generated by qmake (3.0) lun mag 2 09:41:01 2016
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = ImageGallery
INCLUDEPATH += .

# Input
HEADERS += myWindow.h cercaThread.h dialog.h
SOURCES += imagegallery.cpp myWindow.cpp cercaThread.cpp dialog.cpp

DESTDIR = ../../QT/output_ImageGallery
